# Generated by Django 4.2.3 on 2023-07-05 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreImg', models.CharField(max_length=300)),
                ('numRevisiones', models.IntegerField()),
                ('inferencia', models.CharField(max_length=3500)),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correcion', models.CharField(max_length=3500)),
                ('fechaRevision', models.DateTimeField()),
                ('imagen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.imagen')),
                ('usuario', models.ForeignKey(on_delete=models.SET(0), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
