# Generated by Django 4.2.3 on 2023-07-14 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_revision_fechaasignacion_revision_pendiente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='maxRevisiones',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
