# Generated by Django 4.2.3 on 2023-07-14 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_imagen_maxrevisiones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='maxRevisiones',
            field=models.IntegerField(default=100),
        ),
    ]
