# Generated by Django 4.2.3 on 2023-07-14 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_imagen_maxrevisiones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='correcion',
            field=models.CharField(default='', max_length=3500),
        ),
    ]
